name: surfvault
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      - IS_DOCKER=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/surfvault?schema=public
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - db
      - minio
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surfvault
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env.local
    volumes:
      - minio_storage:/data
volumes:
  postgres-data:
  minio_storage:
